apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-https
  namespace: web
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.passthrough: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: minikube.tofunk.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8443


